openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: OpenAPI for taxes management
  version: 0.1.0

servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0/taxes
- description: serverless offline
  url: http://localhost:4000/dev/taxes

paths:
  /taxes:
    $ref: "taxes.yml"
  /taxes/{id}:
    $ref: "taxesByID.yml"